### PR TITLE
About Favorite Artist

### PR DESCRIPTION
**Pull request by kishimoto555555**
related issue: #2 
I add the link and designed the letters. Please check it.

### CODE REVIEW

**Review by oladhari — APPROVED** [review]
LGTM

**Comment by oladhari** [comment]
did you call the commit index.html ?
you should use more meaningful description to your commit, so when you debug it will be easier to find out where you have introduced a modified code, the commit message should describe the changes that have been done, here for example, `adding youtube links to music bands and update related design`

**Comment by oladhari** [comment]
and when you create a PR please assign yourself to the PR and add the related issue in the description so the reviewer can refer directly to the issue, thank you

**Comment by kishimoto555555** [comment]
Thank you for your advice. I noticed I had mistook the commit after I called the commit.
Can I merge the commit??

**Comment by oladhari** [comment]
it is already merged

**Comment by oladhari** [comment]
just go back to the master branch and update your master branch with the remote one

**Comment by kishimoto555555** [comment]
Maybe I did what you said.

**Comment by oladhari** [comment]
```console
git checkout master
git pull
git fetch --all
```

**Comment by kishimoto555555** [comment]
Thank you. I did it.

**Pull request merged**
